"""Generate report tables and comparisons from the completed occupation data."""

from pathlib import Path
import json

import numpy as np

from .qns27 import cluster

ROOT = Path(__file__).resolve().parents[1]
RESULT = ROOT / "result"
NEW = RESULT / "data/v5_qns27_importance_obdm/final"
OLD = RESULT / "data/v4_qns27_observables"


def value_error(value, error):
    center = np.format_float_positional(
        value, precision=3, unique=False, fractional=False, trim="k"
    )
    uncertainty = np.format_float_positional(
        error, precision=2, unique=False, fractional=False, trim="k"
    )
    return rf"{center}\mathbin{{\pm}}{uncertainty}"


def main():
    status = json.loads((NEW / "status.json").read_text())
    if status["status"] != "complete":
        raise RuntimeError("All ten occupation calculations must finish first")
    ed = json.loads((RESULT / "data/fig5_27cell_observables.json").read_text())
    rotation = np.asarray(cluster().rotation60)
    rotation = rotation[rotation]
    records = {}
    rows = []
    labels = [("full_m", r"full $M$"), ("v4_gamma", r"$P_\Gamma[M]$")]
    labels += [(f"v4_outer_c3_p{m}", rf"$P_{m}P_\Gamma[M]$") for m in range(3)]
    for filling, prefix in (("1/3", "nu1of3"), ("2/3", "nu2of3")):
        if rows:
            rows.append(r"\midrule")
        target = np.asarray(ed["fillings"][filling]["n_k"])
        for suffix, label in labels:
            stem = f"{prefix}_{suffix}"
            meta = json.loads((NEW / stem / "qns27_diagnostics.json").read_text())
            old_meta = json.loads((OLD / stem / "qns27_diagnostics.json").read_text())
            with np.load(NEW / stem / "qns27_diagnostics.npz") as z, np.load(
                OLD / stem / "qns27_diagnostics.npz"
            ) as old:
                n1 = z["momentum_occupation_band1_raw"]
                nt = z["momentum_occupation_first_five_raw"]
                rec = {
                    "trace": float(nt.sum()),
                    "trace_sem": float(z["momentum_occupation_first_five_raw_sum_sem"]),
                    "old_trace": old_meta["projected_trace"],
                    "old_trace_sem": old_meta["momentum_occupation_first_five_raw_sum_sem"],
                    "n1_sum": float(n1.sum()),
                    "ed_n1_rms": float(np.sqrt(np.mean((n1 - target) ** 2))),
                    "ed_n1_pearson": float(np.corrcoef(n1, target)[0, 1]),
                    "band_weight_percent": (100 * z["band_weight"]).tolist(),
                    "band_weight_sem_percent": (100 * z["band_weight_sem"]).tolist(),
                    "orbital_normalization_max_error": meta["auxiliary_orbital_normalization_max_error"],
                    "normalization_control_max_change": float(np.max(np.abs(
                        z["one_body_density_diagonal"]
                        - z["one_body_density_diagonal_unnormalized_importance"]
                    ))),
                }
                for name, v in (("n1", n1), ("ntotal", nt)):
                    key = "band1" if name == "n1" else "first_five"
                    rawkey = f"momentum_occupation_{key}_raw"
                    rec[name + "_mean_sem"] = float(z[rawkey + "_sem"].mean())
                    rec[name + "_old_mean_sem"] = float(old[rawkey + "_sem"].mean())
                    rec[name + "_sem_reduction_percent"] = 100 * (
                        1 - rec[name + "_mean_sem"] / rec[name + "_old_mean_sem"]
                    )
                    rec[name + "_c3_max"] = float(np.max(np.abs(v - v[rotation])))
                    rec[name + "_c3_rms"] = float(np.sqrt(np.mean((v - v[rotation]) ** 2)))
                    rec[name + "_c3_max_z"] = meta[f"{rawkey}_c3_max_z"]
                records[stem] = rec
                values = [rf"${filling}$", label, "$" + value_error(rec["trace"], rec["trace_sem"]) + "$"]
                values += ["$" + value_error(w, s) + "$" for w, s in zip(
                    rec["band_weight_percent"], rec["band_weight_sem_percent"]
                )]
                rows.append(" & ".join(values) + r"\\")

    (RESULT / "neural_bloch_importance_table.tex").write_text(
        "% Generated by src.summarize_importance_obdm; do not edit numbers.\n"
        + r"""\begin{table}[H]
\centering
\caption{Updated 27-cell five-band projection: 20,640 configurations from
4,128 frozen chains, 64 importance draws per configuration, and 32 blocks
containing complete walker histories. $T_5$ is the physical five-band trace;
$W_n$ are percentages of $N_e$. Errors are block SEMs, without a trace
constraint or positivity clipping.}
\label{tab:qns27-rdm}
\resizebox{\columnwidth}{!}{%
\begin{tabular}{@{}llrrrrrr@{}}
\toprule
$\nu$ & state & $T_5$ & $W_1$ & $W_2$ & $W_3$ & $W_4$ & $W_5$\\
\midrule
""" + "\n".join(rows) + "\n" + r"""\bottomrule
\end{tabular}%
}
\end{table}
"""
    )
    first = records["nu1of3_v4_outer_c3_p0"]
    second = records["nu2of3_v4_outer_c3_p1"]
    outer = [v for k, v in records.items() if "outer_c3" in k]
    profiles = []
    for filling, m, r in (("1/3", 0, first), ("2/3", 1, second)):
        profiles.append(
            rf"For the selected $\nu={filling}$, $m={m}$ branch, the updated "
            rf"physical band-1 profile has RMS difference {r['ed_n1_rms']:.3f} "
            rf"and Pearson correlation {r['ed_n1_pearson']:.3f} with the "
            rf"one-band ED reference, and its momentum sum is {r['n1_sum']:.4f}. "
            rf"The maximum raw $C_3$ partner differences are {r['n1_c3_max']:.4f} "
            rf"for $n_1$ and {r['ntotal_c3_max']:.4f} for $n_{{\rm tot}}$. "
            rf"Using the covariance of the paired block estimates gives "
            rf"maximum standardized differences {r['n1_c3_max_z']:.2f} and "
            rf"{r['ntotal_c3_max_z']:.2f}, respectively."
        )
    profiles.append(
        r"These comparisons use the raw multiband-QNS projections and the "
        r"one-band ED manifold-averaged profile. They involve both band mixing "
        r"and different state/ensemble definitions; their differences are not "
        r"a pure Monte Carlo error or a matched-Hamiltonian convergence test."
    )
    profiles.append(
        rf"Across all six outer states, maximum raw $n_1$ partner differences "
        rf"span {min(r['n1_c3_max'] for r in outer):.4f}--{max(r['n1_c3_max'] for r in outer):.4f}; "
        rf"the corresponding $n_{{\rm tot}}$ range is "
        rf"{min(r['ntotal_c3_max'] for r in outer):.4f}--{max(r['ntotal_c3_max'] for r in outer):.4f}. "
        rf"The largest paired-block standardized differences are "
        rf"{max(r['n1_c3_max_z'] for r in outer):.2f} and "
        rf"{max(r['ntotal_c3_max_z'] for r in outer):.2f}. "
        r"Individual large residuals must be interpreted with the many "
        r"correlated momentum/sector comparisons and the sampling limitations "
        r"below; the calculation does not establish that all remaining "
        r"asymmetry is independent Gaussian noise."
    )
    (RESULT / "neural_bloch_importance_profiles.tex").write_text("\n\n".join(profiles) + "\n")

    analysis = []
    for filling, m, r in (("1/3", 0, first), ("2/3", 1, second)):
        analysis.append(
            rf"For $\nu={filling},m={m}$, the mean pointwise $n_1$ SEM changes "
            rf"from {r['n1_old_mean_sem']:.4f} to {r['n1_mean_sem']:.4f}, "
            rf"and the $n_{{\rm tot}}$ SEM from {r['ntotal_old_mean_sem']:.4f} "
            rf"to {r['ntotal_mean_sem']:.4f}. The five-band trace changes from "
            rf"${value_error(r['old_trace'],r['old_trace_sem'])}$ to "
            rf"${value_error(r['trace'],r['trace_sem'])}$."
        )
    for filling, prefix in (("1/3", "nu1of3"), ("2/3", "nu2of3")):
        selected = [v for k, v in records.items() if k.startswith(prefix)]
        analysis.append(
            rf"At $\nu={filling}$ the five new traces span "
            rf"{min(r['trace'] for r in selected):.4f}--{max(r['trace'] for r in selected):.4f}."
        )
    analysis.append(
        rf"Across all ten states the mean pointwise SEM reduction is "
        rf"{min(r['n1_sem_reduction_percent'] for r in records.values()):.1f}--"
        rf"{max(r['n1_sem_reduction_percent'] for r in records.values()):.1f}\% for $n_1$, "
        rf"and {min(r['ntotal_sem_reduction_percent'] for r in records.values()):.1f}--"
        rf"{max(r['ntotal_sem_reduction_percent'] for r in records.values()):.1f}\% for $n_{{\rm tot}}$. "
        r"This compares the complete old and new protocols (including different "
        r"sample counts and eight versus 32 blocks), not an isolated test of "
        r"importance sampling at equal cost. The number of nonlocal ratio "
        r"evaluations per state increases from 528,384 to 1,320,960, a factor 2.5."
    )
    analysis.append(
        rf"The maximum auxiliary orbital-normalization error is "
        rf"{max(r['orbital_normalization_max_error'] for r in records.values()):.5f}; "
        rf"the largest change of a single band/momentum diagonal produced by "
        rf"this control is {max(r['normalization_control_max_change'] for r in records.values()):.5f}. "
        r"The uncorrected importance estimates remain in the released data "
        r"for comparison. Small negative remote-band estimates are retained "
        r"as evidence of finite-estimator uncertainty."
    )
    (RESULT / "neural_bloch_importance_comparison.tex").write_text("\n\n".join(analysis) + "\n")
    out = {"status": "complete", "states": records}
    (NEW / "comparison.json").write_text(json.dumps(out, indent=2) + "\n")
    print(json.dumps(out, indent=2))


if __name__ == "__main__":
    main()
